---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-helm
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: False
  options:
    vvv: True
lint: |
  yamllint .
  ansible-lint
verifier:
  name: ansible
