---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-helm
    image: ghcr.io/avnes/molecule-ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
  options:
    vvv: True
lint: |
  yamllint .
  ansible-lint
verifier:
  name: ansible
