name: Auto release on merge

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.yamllint'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
      
  workflow_dispatch:

jobs:
  shared:
    uses: avnes/actions-workflows/.github/workflows/auto-release-on-merge.yaml@main
