name: Publish to Ansible Galaxy

on:
  workflow_run:
    workflows: ["Auto release on merge"]
    types:
      - completed
    
  workflow_dispatch:

jobs:
  shared:
    uses: avnes/actions-workflows/.github/workflows/ansible-publish.yaml@main
    secrets: inherit
